// <auto-generated />
using System;
using System.Collections.Generic;
using Enlyce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enlyce.Infrastructure.Migrations
{
    [DbContext(typeof(EnlyceDbContext))]
    partial class EnlyceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enlyce.Domain.Entities.Inmueble", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Banos")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVentaArriendo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FotosCount")
                        .HasColumnType("integer");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("integer");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("integer");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Parqueaderos")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Direccion", "Enlyce.Domain.Entities.Inmueble.Direccion#Direccion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Barrio")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Barrio");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Ciudad");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Precio", "Enlyce.Domain.Entities.Inmueble.Precio#Dinero", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Precio");
                        });

                    b.HasKey("Id");

                    b.ToTable("Inmuebles", (string)null);
                });

            modelBuilder.Entity("Enlyce.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AsesorAsignadoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutorizacionDatos")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimoContacto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotivoCierre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NotasCierre")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Enlyce.Domain.Entities.Lead.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Telefono", "Enlyce.Domain.Entities.Lead.Telefono#Telefono", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Telefono");
                        });

                    b.HasKey("Id");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("Enlyce.Domain.Entities.Propietario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Enlyce.Domain.Entities.Propietario.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Telefono", "Enlyce.Domain.Entities.Propietario.Telefono#Telefono", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Telefono");
                        });

                    b.HasKey("Id");

                    b.ToTable("Propietarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
