/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObtenerAlertas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RegisterAsesor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeedAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/inmuebles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPublicProperties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/inmuebles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPublicPropertyBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datos-personales/{leadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConsultarDatosLead"];
        put?: never;
        post?: never;
        delete: operations["SuprimirDatosLead"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inmuebles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetInmuebleById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inmuebles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateInmueble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interacciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RegistrarInteraccion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interacciones/lead/{leadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObtenerInteraccionesPorLead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetLeadById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConsultarPipeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/{id}/mover-etapa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MoverEtapa"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/{id}/asignar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["AsignarLead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/{id}/reasignar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ReasignarLead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/politica/activa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPoliticaActiva"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publicaciones/{publicationId}/fotos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UploadPublicationPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publicaciones/{publicationId}/fotos/restricciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMediaConstraints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visitas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObtenerVisitas"];
        put?: never;
        post: operations["RegistrarVisita"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visitas/lead/{leadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObtenerVisitasPorLead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visitas/asesor/{asesorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObtenerVisitasPorAsesor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlertaLeadDto: {
            /** Format: uuid */
            id?: string;
            nombre?: string | null;
            email?: string | null;
            etapaPipeline?: string | null;
            /** Format: date-time */
            fechaUltimaActividad?: string;
            /** Format: int32 */
            diasSinActividad?: number;
        };
        AlertasResponse: {
            leads?: components["schemas"]["AlertaLeadDto"][] | null;
            /** Format: int32 */
            total?: number;
        };
        AsignarLeadRequest: {
            /** Format: uuid */
            asesorId?: string;
        };
        ConsentimientoInfo: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            fecha?: string;
            versionPolitica?: string | null;
            metodo?: string | null;
        };
        ConsultarDatosLeadResponse: {
            /** Format: uuid */
            id?: string;
            nombre?: string | null;
            email?: components["schemas"]["Email"];
            telefono?: components["schemas"]["Telefono"];
            autorizacionDatos?: boolean;
            consentimiento?: components["schemas"]["ConsentimientoInfo"];
        };
        CreateInmuebleRequest: {
            nombre?: string | null;
            descripcion?: string | null;
            tipo?: components["schemas"]["TipoInmueble"];
            modalidad?: components["schemas"]["ModalidadInmueble"];
            calle?: string | null;
            ciudad?: string | null;
            barrio?: string | null;
            /** Format: double */
            precio?: number;
            moneda?: string | null;
            /** Format: int32 */
            metrosCuadrados?: number;
            /** Format: int32 */
            habitaciones?: number;
            /** Format: int32 */
            banos?: number;
            /** Format: int32 */
            parqueaderos?: number;
            /** Format: uuid */
            propietarioId?: string;
        };
        CreateInmuebleResponse: {
            /** Format: uuid */
            id?: string;
            nombre?: string | null;
            tipo?: string | null;
            modalidad?: string | null;
            direccion?: string | null;
            /** Format: double */
            precio?: number;
            /** Format: date-time */
            fechaCreacion?: string;
        };
        CreateLeadRequest: {
            nombre?: string | null;
            email?: string | null;
            telefono?: string | null;
            fuente?: string | null;
            autorizacionDatos?: boolean;
            tipoOperacion?: string | null;
            ownerService?: string | null;
            publicationId?: string | null;
        };
        CreateLeadResponse: {
            /** Format: uuid */
            id?: string;
            nombre?: string | null;
            email?: string | null;
            estado?: string | null;
            /** Format: date-time */
            fechaCreacion?: string;
            ownerService?: string | null;
            /** Format: uuid */
            publicationId?: string | null;
        };
        Email: {
            readonly value?: string | null;
        };
        EtapaPipelineDto: {
            nombre?: string | null;
            etiqueta?: string | null;
            /** Format: int32 */
            leadCount?: number;
        };
        GetInmuebleByIdResponse: {
            /** Format: uuid */
            id?: string;
            nombre?: string | null;
            descripcion?: string | null;
            tipo?: string | null;
            modalidad?: string | null;
            estado?: string | null;
            direccion?: string | null;
            /** Format: double */
            precio?: number;
            moneda?: string | null;
            /** Format: int32 */
            metrosCuadrados?: number;
            /** Format: int32 */
            habitaciones?: number;
            /** Format: int32 */
            banos?: number;
            /** Format: int32 */
            parqueaderos?: number;
            /** Format: uuid */
            propietarioId?: string;
            /** Format: date-time */
            fechaCreacion?: string;
            activo?: boolean;
        };
        GetLeadByIdResponse: {
            /** Format: uuid */
            id?: string;
            nombre?: string | null;
            email?: string | null;
            telefono?: string | null;
            fuente?: string | null;
            estado?: string | null;
            motivoCierre?: string | null;
            /** Format: date-time */
            fechaCreacion?: string;
            /** Format: date-time */
            fechaUltimoContacto?: string | null;
            autorizacionDatos?: boolean;
            activo?: boolean;
            etapaPipeline?: string | null;
            tipoOperacion?: string | null;
            ownerService?: string | null;
            /** Format: uuid */
            publicationId?: string | null;
        };
        HttpValidationProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
        Interaccion: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly leadId?: string;
            /** Format: uuid */
            readonly asesorId?: string;
            readonly tipo?: string | null;
            readonly resumen?: string | null;
            /** Format: date-time */
            readonly fecha?: string;
        };
        LeadDto: {
            /** Format: uuid */
            id?: string;
            nombre?: string | null;
            email?: string | null;
            telefono?: string | null;
            fuente?: string | null;
            etapaPipeline?: string | null;
            tipoOperacion?: string | null;
            /** Format: int32 */
            interaccionesCount?: number;
            /** Format: date-time */
            fechaUltimaInteraccion?: string | null;
            /** Format: date-time */
            fechaCreacion?: string;
            asesorNombre?: string | null;
        };
        LoginCommand: {
            correo?: string | null;
            password?: string | null;
        };
        MediaConstraintsResponse: {
            tiposPermitidos?: string[] | null;
            /** Format: int64 */
            maxBytes?: number;
            /** Format: int32 */
            anchoMinimo?: number;
            /** Format: int32 */
            altoMinimo?: number;
            /** Format: int32 */
            dimensionMaxima?: number;
            /** Format: int32 */
            maxFotosPorPublicacion?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ModalidadInmueble: 0 | 1 | 2;
        MoverEtapaRequest: {
            nuevaEtapa?: string | null;
        };
        ObtenerPoliticaActivaResponse: {
            /** Format: uuid */
            id?: string;
            version?: string | null;
            textoCompleto?: string | null;
            /** Format: date-time */
            fechaVigencia?: string;
        };
        PhotoVariantResponse: {
            url?: string | null;
            /** Format: int32 */
            width?: number;
        };
        PipelineResponse: {
            etapas?: components["schemas"]["EtapaPipelineDto"][] | null;
            leads?: components["schemas"]["LeadDto"][] | null;
            /** Format: int32 */
            total?: number;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        PublicAdvisorResponse: {
            /** Format: uuid */
            id?: string;
            displayName?: string | null;
            publicPhone?: string | null;
        };
        PublicCoverPhotoResponse: {
            url?: string | null;
            altText?: string | null;
        };
        PublicLocationResponse: {
            municipality?: string | null;
            neighborhood?: string | null;
            /** Format: double */
            approximateLatitude?: number;
            /** Format: double */
            approximateLongitude?: number;
        };
        PublicMoneyResponse: {
            /** Format: double */
            amount?: number;
            currency?: string | null;
        };
        PublicPhotoResponse: {
            url?: string | null;
            altText?: string | null;
            /** Format: int32 */
            order?: number;
            isCover?: boolean;
        };
        PublicPropertyDetailResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string | null;
            publicTitle?: string | null;
            publicDescription?: string | null;
            propertyType?: string | null;
            operation?: string | null;
            price?: components["schemas"]["PublicMoneyResponse"];
            administrationFee?: components["schemas"]["PublicMoneyResponse"];
            location?: components["schemas"]["PublicLocationResponse"];
            features?: components["schemas"]["PublicPropertyFeaturesResponse"];
            photos?: components["schemas"]["PublicPhotoResponse"][] | null;
            advisor?: components["schemas"]["PublicAdvisorResponse"];
            /** Format: date-time */
            publishedAt?: string;
        };
        PublicPropertyFeaturesResponse: {
            /** Format: int32 */
            areaSquareMeters?: number;
            /** Format: int32 */
            bedrooms?: number;
            /** Format: int32 */
            bathrooms?: number;
            /** Format: int32 */
            parkingSpaces?: number;
            /** Format: int32 */
            stratum?: number | null;
            amenities?: string[] | null;
        };
        PublicPropertyListItemResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string | null;
            publicTitle?: string | null;
            propertyType?: string | null;
            operation?: string | null;
            price?: components["schemas"]["PublicMoneyResponse"];
            location?: components["schemas"]["PublicLocationResponse"];
            /** Format: int32 */
            areaSquareMeters?: number;
            /** Format: int32 */
            bedrooms?: number;
            /** Format: int32 */
            bathrooms?: number;
            /** Format: int32 */
            parkingSpaces?: number;
            coverPhoto?: components["schemas"]["PublicCoverPhotoResponse"];
            /** Format: date-time */
            publishedAt?: string;
        };
        PublicPropertyPageResponse: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            total?: number;
            items?: components["schemas"]["PublicPropertyListItemResponse"][] | null;
        };
        ReasignarLeadRequest: {
            /** Format: uuid */
            nuevoAsesorId?: string;
        };
        RegisterAsesorCommand: {
            nombre?: string | null;
            correo?: string | null;
            password?: string | null;
            rol?: string | null;
        };
        RegistrarInteraccionRequest: {
            /** Format: uuid */
            leadId?: string;
            /** Format: uuid */
            asesorId?: string;
            tipo?: string | null;
            resumen?: string | null;
        };
        RegistrarVisitaRequest: {
            /** Format: uuid */
            leadId?: string;
            /** Format: uuid */
            inmuebleId?: string;
            /** Format: uuid */
            asesorId?: string;
            /** Format: date-time */
            fechaProgramada?: string;
        };
        Telefono: {
            readonly value?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        TipoInmueble: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        UploadPublicationPhotoResponse: {
            /** Format: uuid */
            publicationId?: string;
            url?: string | null;
            altText?: string | null;
            /** Format: int32 */
            order?: number;
            isCover?: boolean;
            /** Format: int32 */
            width?: number;
            /** Format: int32 */
            height?: number;
            variants?: components["schemas"]["PhotoVariantResponse"][] | null;
        };
        Visita: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly leadId?: string;
            /** Format: uuid */
            readonly inmuebleId?: string;
            /** Format: uuid */
            readonly asesorId?: string;
            /** Format: date-time */
            readonly fechaProgramada?: string;
            /** Format: date-time */
            readonly fechaRealizada?: string | null;
            readonly feedback?: string | null;
            readonly estado?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ObtenerAlertas: {
        parameters: {
            query?: {
                DiasUmbral?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertasResponse"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RegisterAsesor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAsesorCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeedAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetPublicProperties: {
        parameters: {
            query?: {
                Page?: number;
                PageSize?: number;
                Operation?: string;
                PropertyType?: string;
                Municipality?: string;
                Neighborhood?: string;
                MinPrice?: number;
                MaxPrice?: number;
                MinArea?: number;
                MaxArea?: number;
                Bedrooms?: number;
                Bathrooms?: number;
                ParkingSpaces?: number;
                Sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPropertyPageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetPublicPropertyBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPropertyDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ConsultarDatosLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultarDatosLeadResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SuprimirDatosLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    HealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetInmuebleById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInmuebleByIdResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateInmueble: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInmuebleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInmuebleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RegistrarInteraccion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarInteraccionRequest"];
            };
        };
        responses: {
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ObtenerInteraccionesPorLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Interaccion"][];
                };
            };
        };
    };
    GetLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLeadByIdResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateLead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeadRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateLeadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ConsultarPipeline: {
        parameters: {
            query?: {
                Etapa?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
        };
    };
    MoverEtapa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoverEtapaRequest"];
            };
        };
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AsignarLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsignarLeadRequest"];
            };
        };
        responses: {
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReasignarLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasignarLeadRequest"];
            };
        };
        responses: {
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetPoliticaActiva: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObtenerPoliticaActivaResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UploadPublicationPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicationId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    archivo: string;
                    textoAlternativo: string;
                    esPortada: boolean;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadPublicationPhotoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetMediaConstraints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaConstraintsResponse"];
                };
            };
        };
    };
    ObtenerVisitas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visita"][];
                };
            };
        };
    };
    RegistrarVisita: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarVisitaRequest"];
            };
        };
        responses: {
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ObtenerVisitasPorLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visita"][];
                };
            };
        };
    };
    ObtenerVisitasPorAsesor: {
        parameters: {
            query: {
                Desde: string;
            };
            header?: never;
            path: {
                asesorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visita"][];
                };
            };
        };
    };
}
